#ifndef SETTINGS_H
#define SETTINGS_H

#define COUNTDOWN_DURATION 5000
#define MAX_PLAYER 3

#define MENU_BUTTON_PIN D6
#define PAD_A_PIN D5
#define PAD_B_PIN D7
#define PAD_C_PIN D4
#define PAD_D_PIN
#define LONG_PRESS_DELAY 200

#define TIMER_UPDATE_INTERVAL 50

#endif